version: "3.7"

services:
  web:
    build: flask
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DEBUG=1
    networks:
      - flask_network

  nginx:
    build: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - flask_network

networks:
  flask_network:
