version: "3.7"

services:
  web:
    build: ./flask
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DEBUG=1
    volumes:
      - ./flask:/run
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    networks:
      - flask_network

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./entrypoint.sh:/entrypoint.sh
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
